openapi: '3.0.2'
info:
  title: Openbox Backend Internal API
  version: '1.0'
servers:
  - url: https://localhost:8080/api
paths:
  /process/application/leave-application:
    put:
      description: User initiate a new leave application with required information.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./models/LeaveApplication.yml#/components/schemas/PutLeaveApplication"
              
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: './models/Application.yml#/components/schemas/Application' 
                  - $ref: './models/LeaveApplication.yml#/components/schemas/LeaveApplication' 
                
  /process/application/{applicationId}/permit:
    post:
      description: 'Permit an application by manager. The api can only be triggered by the applicant''s manager'
      parameters:
        - in: path
          name: applicationId
          schema:
            type: integer
          required: true
          description: The id of the application.
      responses:
        '200':
          description: OK
  
  /process/application/{applicationId}/reject:
    post:
      description: 'Reject an application by manager. The api can only be triggered by the applicant''s manager'
      parameters:
        - in: path
          name: applicationId
          schema:
            type: integer
          required: true
          description: "The ID of the application."
      requestBody:
        content:
          text/plain:
            schema:
              type: string
            example: "The leave time is obscured. Please indicate a precise time"
      responses:
        '200':
          description: OK