components:
  schemas:
    LeaveApplication:
      type: object
      properties:
        leaveType:
          type: string
          description: The type of the leave application, including "SICK" and "PERSONAL"
          enum:
            - SICK
            - PERSONAL
        startDate: 
          type: string
          description: The start date time of the leave. The date time follow the ISO 8601 format.
          example: "2024-03-31T08:30:00-07:00"
        endDate:
          type: string
          description: An ISO standard time string of the leave end time
          example: "2024-03-31T18:00:00-07:00"
        currentHandler:
          type: string
          description: The username of the current handler of the Leave application. Current handler is the initiator when the application is initiating or end.
          example: raynold
    PutLeaveApplication:
      properties:
        applicant:
          $ref: "./Application.yml#/components/schemas/Application/properties/applicant"
        leaveType: 
          $ref: "#/components/schemas/LeaveApplication/properties/leaveType"
        reason:
          $ref: "./Application.yml#/components/schemas/Application/properties/reason"
        startDate: 
          $ref: "#/components/schemas/LeaveApplication/properties/startDate"
        endDate:
          $ref: "#/components/schemas/LeaveApplication/properties/endDate"
      required:
        - applicant
        - leaveType
        - startDate
        - endDate
        - Timezone